spring.application.name=hostel-finder-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hostel_finder
spring.datasource.username=root
spring.datasource.password=Venky@2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//jwt
jwt.secret=mySuperStrongSecretKeyForJwt123456789
jwt.expiration=3600000